import axios from 'axios';
import logger from '../utils/logger.js';

// Validate URL by checking if it's accessible
const validateUrl = async (req, res) => {
  try {
    const { url, presignedUrl, sei_check = false, checkDimensions = true, streamId = '' } = req.body;
    
    // Accept either 'url' or 'presignedUrl' parameter
    const targetUrl = url || presignedUrl;

    if (!targetUrl) {
      return res.status(400).json({
        success: false,
        message: 'URL or presignedUrl is required'
      });
    }

    // Check if it's a GCS presigned URL
    const isGCSPresignedUrl = targetUrl.includes('storage.googleapis.com');
    
    if (isGCSPresignedUrl) {
      // For GCS presigned URLs, validate the URL format and assume it's valid
      // since it was generated by our own storage service
      try {
        const urlObj = new URL(targetUrl);
        
        // Basic validation response for presigned URLs
        const validationResult = {
          success: true,
          message: 'Presigned URL is valid',
          data: {
            isValid: true,
            url: targetUrl,
            contentType: 'application/octet-stream', // Default for presigned URLs
            result: {
              video: checkDimensions ? [{
                width: 1920, // Default values - in production, use actual video analysis
                height: 1080,
                duration: 0
              }] : []
            }
          }
        };

        // Add aspect ratio if checking dimensions
        if (checkDimensions) {
          const aspectRatio = '16:9'; // Default - in production, calculate from actual dimensions
          validationResult.data.aspectRatio = aspectRatio;
          validationResult.data.dimensions = { width: 1920, height: 1080 };
        }

        return res.status(200).json(validationResult);
      } catch (urlParseError) {
        logger.error('Invalid presigned URL format:', urlParseError.message);
        return res.status(400).json({
          success: false,
          message: 'Invalid presigned URL format',
          data: ''
        });
      }
    }

    // For non-presigned URLs, check if URL is accessible
    try {
      const response = await axios.head(targetUrl, {
        timeout: 10000,
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
      });

      if (response.status === 200) {
        const contentType = response.headers['content-type'] || '';
        const contentLength = response.headers['content-length'] || 0;

        // Basic validation response
        const validationResult = {
          success: true,
          message: 'URL is valid and accessible',
          data: {
            isValid: true,
            contentType,
            contentLength: parseInt(contentLength),
            url: targetUrl,
            result: {
              video: checkDimensions ? [{
                width: 1920, // Default values - in production, use actual video analysis
                height: 1080,
                duration: 0
              }] : []
            }
          }
        };

        // Add aspect ratio if checking dimensions
        if (checkDimensions) {
          const aspectRatio = '16:9'; // Default - in production, calculate from actual dimensions
          validationResult.data.aspectRatio = aspectRatio;
          validationResult.data.dimensions = { width: 1920, height: 1080 };
        }

        res.status(200).json(validationResult);
      } else {
        res.status(400).json({
          success: false,
          message: 'URL is not accessible',
          data: ''
        });
      }
    } catch (urlError) {
      logger.error('URL validation failed:', urlError.message);
      res.status(400).json({
        success: false,
        message: 'URL validation failed - URL is not accessible or invalid',
        data: ''
      });
    }

  } catch (error) {
    logger.error('Error in URL validation:', error);
    res.status(500).json({
      success: false,
      message: 'An error occurred while validating the URL',
      data: ''
    });
  }
};

export {
  validateUrl
};