import mongoose from "mongoose";

const clipSchema = new mongoose.Schema(
  {
    streamId: { type: String, required: true },
    id: {
      type: String,
      default: "",
      required: true,
      unique: true,
      index: true,
    },
    contentProvider: { type: String, default: "zentag" },
    title: { type: String, default: "", required: true },
    // episodeTitle: { type: String, default: "" },
    // brandSafetyData: { type: Array, default: [] },
    // promoUrls: { type: Array, default: [] },
    clipIdArr: { type: Array, default: [] },
    // videoSceneArray: { type: Array, default: [] },
    // brandSafetyPerform: { type: Boolean, default: false },
    isHighlightVideo: { type: Boolean, default: false },
    cmsPublish: { type: Boolean, default: false },
    competitionId: { type: String, default: "" },
    publishDate: { type: String, default: "" },
    publishTime: { type: String, default: "" },
    endDateTime: { type: String, default: "" },
    objectSubtype: { type: String, default: "SPORTS_CLIPS" },
    properties: {
      type: String,
      default: "_in,_pk,_lk,_np,_bd,_bt,_af,_mm,_mu",
    },
    tags: { type: Array, default: [] },
    duration: { type: Number, default: 0, required: true },
    timeTaken: { type: Number, default: 0 },
    timeTakenClipsQ: { type: Number, default: 0 },
    timeTakenClipsAI: { type: Number, default: 0 },
    start_time: { type: String, required: true },
    end_time: { type: String, required: true },
    tvBackgroundImage: {
      type: String,
      default:
        "https://origin-staticv2.sonyliv.com/videoasset_images/KFC_BBL_M42_STARS_VS_RENEGADES_HATCHER_SPL_17012021_TVBG.jpg",
    },
    // videoThumbnailUrl: { type: String, default: "" },
    videoUrl: { type: String, default: "" },
    videoUrl480P: { type: String, default: "" },
    potriat_video_url: { type: String, default: "" },
    s3_video_url: { type: String, default: "" },
    s3_thumb_url: { type: String, default: "" },
    aiCricketEvent: { type: String, default: "" },
    story_title: { type: String, default: "" },
    story_published_status: { type: String, default: "unpublished" },
    story_published_time: { type: String, default: "" },
    story_score: { type: Object, default: {} },
    // videoThumbnailUrls: { type: Array, default: [] },
    generatedThumbnailUrls: { type: Array, default: [] },
    clipData: { type: Object, default: {} },
    jsonTemplate: { type: Object, default: {} },
    s3Data: { type: Object, default: {} },
    storyPayload: { type: Object, default: {} },
    videosWithSlates: { type: Array, default: [] },
    clipsRanking: { type: Object, default: {} },
    audioArray: { type: Array, default: [] },
    slateVideo: { type: Array, default: [] },
    // sftpLogs: { type: Array, default: [] },
    clipEventsLogs: { type: Object, default: {} },
    description: { type: String, default: "" },
    status: { type: Number, default: 2 }, // 1 == published 2 == unpublished
    customData: {
      language: { type: String, default: "" },
      sportName: { type: String, default: "" },
      players: { type: Array, default: [] },
      aiSceneId: { type: String, default: "" },
      scene_no: { type: String, default: "" },
      clip_ai_outcome: { type: String, default: "" },
      label: { type: String, default: "" },
      clip_ai_score: { type: String, default: "" },
      timestamp: { type: String, default: "" },
    },
    filter: { type: String, default: "" },
    isS3Published: { type: Boolean, default: false },
    isAutoHighlight: { type: Boolean, default: false },
    // isPromoVideo: { type: Boolean, default: false },
    events: { type: Array, default: [] },
    isLiveProcess: { type: Boolean, default: false },
    outputSceneCsvKey: { type: String, default: "" },
    streamTitle: { type: String, default: "" },
    trimUrl: { type: String, default: "" },
    audioClassifcationEvent: { type: String, default: "" },
    aiSceneId: { type: String, default: "" },
    potriat_thumbnail_url: { type: String, default: "" },
    potriat_thumbnail_urls: { type: Array, default: [] },
    editedVideos: { type: Array, default: [] },
    isManual: { type: Boolean, default: true },
    aspectRatio: { type: String, default: "16:9" },
    editedPreviewUrl: { type: String, default: "" },
    referenceClipId: { type: String, default: "" },
    playback_speed: { type: String, default: "all" },
    type: { type: String, default: "" },
    seiStartTime: { type: Array, default: [] },
    seiEndTime: { type: Array, default: [] },
    csvData: { type: Object, default: {} },
    editedClipData: { type: Object, default: {} },
    aiTitle: { type: Object, default: {} },
    isGeneratePreview: { type: Boolean, default: false },
    userId: { type: String, default: "" },
    organization: { type: mongoose.Schema.Types.ObjectId, ref: 'Organization', default: null },
    isManualUpload: { type: Boolean, default: false },
    clipPublished: { type: Array, default: [] },
    lastPublishedDate: { type: String },
    storageConsumed: { type: Number, default: 0 },
    // clipRating: { type: Number, default: 0 },
    reasonForRating: { type: String, default: "" },
    seoObject: { type: Object, default: {} },
    xmlFields: { type: Object, default: {} },
    isFTPPublished: { type: Boolean, default: false },
    isFTPPublishedTime: { type: Date, default: new Date() },
    cutVersion: { type: Number, default: 1 },
    isGlacierStatus: { type: Boolean, default: false },
    opsEmail: { type: String },
    saveVersion: { type: Number, default: 1 },
    totalDurationWithoutBumper: { type: Number, default: 0 },
    downloadedClipCount: { type: Number },
    projectId: { type: String, default: "" },
    cliplistIdArr: { type: Array, default: [] },
    highlightId: { type: Array, default: [] },
    parentHighlightId: {
      type: mongoose.Schema.ObjectId,
      ref: "clipList",
      default: null,
    },
    initialStartTime: { type: Number },
    initialEndTime: { type: Number },
    editClipFilterObject: {
      endPointFeedback: { type: String, default: "" },
      startPointFeedback: { type: String, default: "" },
      isAddedToClipsPage: { type: Boolean, default: false },
      addedToclipsPageTime: { type: Date, default: new Date() },
      isDraft: { type: Boolean, default: false },
      isRollbacked: { type: Boolean, default: false },
    },
    mainVideoUrl: { type: String },
    tlmMarker: { type: Number },
    mxfUrl: { type: String },
    webisodeSceneDetails: { type: Object },
    asset_id: { type: String },
    audioTranscript_api: { type: Object, default: {} },
    audioTranscript_model: { type: Object, default: {} },
    social_media_caption: { type: Object, default: {} },
    social_media_title: { type: Object, default: {} },
    metadata: { type: Object },
    sftpUploadTime: { type: String },
    s3UploadTime: { type: String },
    // entityId: { type: String, required: true },
    extendedClipData: { type: Object },
    customThumbnailUrls: { type: Array, default: [] },
    publishedCustomThumbnailUrls: { type: Array, default: [] },
    customThumbnailStatus: { type: String },
    isAITagged: { type: Boolean, default: false },
    isAiCreated: { type: Boolean, default: false },
    mediaConvertUrls: { type: Array },
    clipLanguage: { type: String, default: "" },
    aiEnhanceStartTime: { type: Number },
    aiEnhanceEndTime: { type: Number },
    tracks: { type: [Object], default: [] },
    fadeInObj: { type: Object },
    clipStatus: {
      type: String,
      enum: ["PROCESSING", "COMPLETED", "FAILED", "CANCELLED"],
      default: "PROCESSING",
    },
    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date, default: null },
    deletedBy: { type: String, default: "" },
    deletedIp: { type: String, default: "" },
    deletedCountry: { type: String, default: "UNKNOWN" },
    updatedBy: { type: String, default: "" },
    updatedIp: { type: String, default: "" },
    updatedCountry: { type: String, default: "UNKNOWN" },
    ext_clip_suggest_id: { type: String, required: false },
    isBookmarked: Boolean,
    datafeed: { type: Object, required: false },
    // Additional fields for zentag compatibility
    jobId: { type: String, index: true },
    thumbnailUrl: { type: String },
    thumbnails: { type: [String], default: [] },
    speed: { type: Number, default: 1 },
    rating: { type: Number, min: 0, max: 5, default: 1 },
    // aiServerResponse: { type: Object, default: {} },
    progress: { type: Number, default: 0, min: 0, max: 100 },
    // errorMessage: { type: String },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: false,
    },
  },
  {
    timestamps: true,
  }
);

// Index for efficient queries
clipSchema.index({ streamId: 1, createdAt: -1 });
clipSchema.index({ status: 1 });
clipSchema.index({
  playback_speed: 1,
});
clipSchema.index({
  rating: 1,
});
clipSchema.index({
  tags: 1,
});
clipSchema.index({
  start_time: 1,
});
clipSchema.index({
  end_time: 1,
});
clipSchema.index({
  aspectRatio: 1,
});
clipSchema.index({ 'clipPublished.publishedAt': -1 });
clipSchema.index({ 'clipPublished.platform': 1 });
clipSchema.index({ 'clipPublished.status': 1 });
clipSchema.index({ organization: 1 });
clipSchema.index({ organization: 1, isDeleted: 1 }); // media-library stats and list
clipSchema.index({ organization: 1, isDeleted: 1, createdAt: -1 }); // media-library list "All" by date
export default mongoose.model("Clip", clipSchema);
